INSERT INTO CATEGORIAS (NOME) VALUES ('Decoração');
INSERT INTO CATEGORIAS (NOME) VALUES ('Video Game');
INSERT INTO CATEGORIAS (NOME) VALUES ('Limpeza e Conservação');
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Playstation 5', 4500.0);
INSERT INTO PRODUTO_CATEGORIA (PRODUTO_ID, CATEGORIA_ID) VALUES (1,2);
