INSERT INTO CATEGORIAS (NOME) VALUES ('Decoração');
INSERT INTO CATEGORIAS (NOME) VALUES ('Video Game');
INSERT INTO CATEGORIAS (NOME) VALUES ('Limpeza e Conservação');
INSERT INTO PRODUTOS (NOME, PRECO) VALUES ('Playstation 5', 4500.0);
INSERT INTO PRODUTOS (NOME, PRECO) VALUES ('Xbox', 3999.99);
INSERT INTO PRODUTOS (NOME, PRECO) VALUES ('Nintendo Mini', 499.0);
INSERT INTO PRODUTO_CATEGORIA (PRODUTO_ID, CATEGORIA_ID) VALUES (1,2);
INSERT INTO PRODUTO_CATEGORIA (PRODUTO_ID, CATEGORIA_ID) VALUES (2,2);
INSERT INTO PRODUTO_CATEGORIA (PRODUTO_ID, CATEGORIA_ID) VALUES (3,2);
INSERT INTO ESTADOS (NOME) VALUES ('ACRE'),('ALAGOAS'),('AMAPÁ'),('AMAZONAS'),('BAHIA'),('CEARÁ'),('DISTRITO FEDERAL'),('ESPÍRITO SANTO'),('GOIÁS'),('MATO GROSSO'),('MATO GROSSO DO SUL'),('MINAS GERAIS'),('PARÁ'),('PARANÁ'),('PARAÍBA'),('PERNAMBUCO'),('PIAUÍ'),('RIO DE JANEIRO'),('RIO GRANDE DO NORTE'),('RIO GRANDE DO SUL'),('SÃO PAULO'),('SANTA CATARINA'),('TOCANTINS'),('RORAIMA'),('RONDÔNIA'),('MARANHÃO'), ('SERGIPE');
INSERT INTO CIDADES (NOME, ESTADO_ID) VALUES ('São Paulo', 21), ('Marília',21), ('Florianópolis',22), ('Rio Branco',1), ('Goiânia', 9); 

